swagger: "2.0"
info:
  description: ""
  version: "214.180423.1" #used for a services API version tracking
  title: "Pre-Release Salesforce Marketing Cloud Transactional Messaging APIs"
#host: "www.exacttargetapis.com" #not required - owned by docs

#####
# Section info is defined by tags and tag objects
#####
tags:
- name: "transactional sends"
- name: "transactional definitions"

schemes:
- "https"
paths:
  /transactionalmessages/v1/email/definition/{tsd_external_key}/send:
    parameters:
      - in: path
        name: tsd_external_key
        description: "your transactional send defintion"
        required: true  #always needed because it's a path paramater
        type: string
    post:
      operationId: transactionalEmailDefinitionSend
      tags: #tags are used to group operations in Swagger UI.
      - "transactional sends"
      summary: "send a transactional email message"
      description: ""
      consumes: #this is the content-type header for the reponse
      - "application/json"
      produces: #this is the content-type header in the request
      - "application/json"
      parameters:
      - in: body
        name: "Send body"
        schema:
          allOf:
          - $ref: '#/definitions/emailRequest'
         # - $ref: '#/definitions/globalSettings'
      responses:
        200:
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/apiResponseBody'
            - $ref: '#/definitions/messageSendResponse'
  /transactionalmessages/v1/email/messagekey/{message_key}/status:
    parameters:
    #  - in: path
    #    name: tsd_external_key
    #    description: "The triggered send defintion"
    #    required: true  #always needed because it's a path paramater
    #    type: string
      - in: path
        name: message_key
        description: "Unique message key to check status"
        required: true  #always needed because it's a path paramater
        type: string
    get:
      tags:
      - "transactional sends"
      summary: "fetches email send status by messageKey (cached)"
      responses:
        200:
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/apiResponseBody'
            - $ref: '#/definitions/messageWebhookResponse'

definitions:
#-- Global Definitions ----------
#--------------------------------
  #globalRequestMessage: skipped due to a nest/shared inheritance model for EmailTo>MessageTo+GlobalTo>GlobalMessage w/o namespace conflicts
  globalRequestTo:
    type: object
    required:
      - messageKey
      - subscriberKey
      - emailAddress
    properties:
      messageKey:
        type: string    
        description: Unique client-provided identifier for a specific message to a recipient that could be used to provide feedback for that specific message.
        example: '9691010a-1e59-48a0-b0d8-67d9a86dc470'
      subscriberKey:
        type: string
        description: a text field that contains a value that uniquely identifies a subscriber in your system. A subscriber key is limited to English characters only.
        example: robertsmith324
  globalRequestAttributes:
    type: object
    description: Key:Value object for subscriber attributes defined for the message
    example: "FirstName:Robert or XMLData:<xml>example</xml>"
#-- Email Definitions ---
#-------------------------
  emailRequestFrom:
    type: object
    properties:
      emailAddress: #email
        type: string
        description: 'For email channel, this would be the from address displayed when email is received. '
        example: 'notifications@nto.com'  
  emailRequestTo:
    type: "object"
    properties:
      emailAddress:
        type: string
        description: Required if no 'subscriberKey'.  The email address of the recipient. 
        example: john.smith@example.com
      #Message:
      #  allOf:
      #   - $ref: '#/definitions/emailRequestMessage'
      attributes:
        $ref: '#/definitions/globalRequestAttributes'
      cc:
        type: array
        items:
          type: string
          example: cc_example@example.com, cc2_example@example.com
          #$ref: '#/definitions/GenericEmailArrayObject'
      bcc:
        type: array
        items:
          type: string
          example: cc_example@example.com, cc2_example@example.com
  emailRequest:
    title: email message Request
    type: object
    properties:
      #From:
      #  allOf: 
      #   - $ref: '#/definitions/globalRequestFrom'
      #   - $ref: '#/definitions/emailRequestFrom'
      #Message:
      #  allOf:
      ##  - $ref: '#/definitions/globalRequestMessage'
      #  - $ref: '#/definitions/emailRequestMessage'
      to:
        type: array
        items:
          allOf: 
            - $ref: '#/definitions/globalRequestTo'
            - $ref: '#/definitions/emailRequestTo'
      attributes:
        allOf:
        - $ref: '#/definitions/globalRequestAttributes'
      #Options:
      #  $ref: '#/definitions/globalRequestOptions'

#---------------------------------
  apiResponseBody:
    type: object
    properties:
      requestId:
        type: string
        format: UUID v4
        example: "ba9633fa-5c8d-4c42-8efa-a16412ac0c53"
      statusCode:
        type: integer
        example: 17
      statusMessage:
        type: string
        example: "Ensure you include all required fields in the body of the request"
  messageSendResponse:
    type: object
    properties:
      responses:
        type: array
        items: 
          type: object
          properties:
            messageKey:
              type: string
              example: "9691010a-1e59-48a0-b0d8-67d9a86dc470"
            errorCode:
              type: integer
            errorMessage:
              type: string
  messageWebhookResponse:
    type: object
    properties:
      type: 
        type: string
        example: "TransactionalSendEvents.EmailSent"
      timestamp:
        type: string
        format: date-time
      compositeId:
        type: string
        example: "tsid.job.list.batch.sub"
      info:
        type: object
        properties:
          messageKey:
            type: string
            format: UUID v4
            example: "9691010a-1e59-48a0-b0d8-67d9a86dc470"
          subscriberKey: 
            type: string
          emailAddress:
            type: string
            example: "john.smith@example.com"


